### PR TITLE
popular section changes added issue no#50

### PR DESCRIPTION
**Pull request by farehax**

### CODE REVIEW

**Comment by farehax** [comment]
@adityakmrmishra plz accept my pr

**Comment by adityakmrmishra** [comment]
Hi, @farehax pls open issue before making pr or atleast provide a description for pr .

**Comment by farehax** [comment]
this issue is already assigned to me by @GuryonAnkit

**Comment by farehax** [comment]
> Hi, @farehax pls open issue before making pr or atleast provide a description for pr .

you can check issue no #50

**Review by GuryonAnkit — APPROVED** [review]

**Comment by adityakmrmishra** [comment]
> > Hi, @farehax pls open issue before making pr or atleast provide a description for pr .
> 
> you can check issue no #50 

From next time provide a small description of

**Comment by adityakmrmishra** [comment]
> > Hi, @farehax pls open issue before making pr or atleast provide a description for pr .
> 
> you can check issue no #50 

From next time remember to put description of pr it's a good practice and mention the issue no in it 🙂

**Pull request merged**
