### PR TITLE
Responsive Navbar

### PR DESCRIPTION
**Pull request by aj12-houdini**
Made the NavBar responsive resolving issue #38 

### Before
Screenshot 2023-10-06 212120

### After
Screenshot 2023-10-06 205416

### CODE REVIEW

**Review by GuryonAnkit — APPROVED** [review]

**Comment by aj12-houdini** [comment]
@GuryonAnkit I resolved it on my local computer. The deployed version after the changes look like this. [Latest Deployed version](https://deploy-preview-39--adityageet.netlify.app/)
Screenshot 2023-10-07 105559

**Comment by GuryonAnkit** [comment]
@aj12-houdini 

In the Android mobile view, the issue is not resolved

**Comment by aj12-houdini** [comment]
@GuryonAnkit Hi thanks for raising my attention to the issue. Hopefully, I have resolved it, sorry for the inconvenience. Can you please check again?

**Review by GuryonAnkit — APPROVED** [review]
Great work!!

**Review by l-ashish-gupta-l — APPROVED** [review]

**Pull request merged**
